### ISSUE TITLE
Output results folders contain blank spaces

### ISSUE THREAD

**Issue by vinod1981** [frankvogt/vcf2gwas#16]
Dear Frank,
In the new version of vcf2gwas, output folder specially Mixed Linear Model contains blank spaces which can't further be used in path without replacing those spaces. Please see the issue!
Another thing is that -q 0.05 still keeping SNPs with <5% MAF which is unusual to me. Please also look into it.
Thanks,

Vinod

**Comment by frankvogt** [comment]
Hi Vinod,
you can always escape the spaces with backslashes or by putting the complete path in quotation marks, but I'll change it back in the next version to not include spaces in the folder names.
Best, 
Frank

**Comment by vinod1981** [comment]
Dear Frank,
Thank you very much for reply. 
I also found that '%' signs in best p-values folder bring issue when I want to extract something out of these files. I have to delete them manually and for 100s of analysis it is a bit time consuming. I feel it should be like previous version.
Thanks,
Vinod

**Comment by krishna1925** [comment]
Hi, 
I had a issue while running vcf2gwas. It worked well in my previous analysis and now, it throws this error!
Traceback (most recent call last):
  File "/home/kpa26/anaconda3/envs/myenv/lib/python3.9/site-packages/vcf2gwas/analysis.py", line 204, in <module>
    raise_error(ValueError, msg, Log)
  File "/home/kpa26/anaconda3/envs/myenv/lib/python3.9/site-packages/vcf2gwas/utils.py", line 147, in raise_error
    raise error(msg)
ValueError: No individuals left! Check if IDs in VCF and phenotype file are of the same format

I double checked all ids in the vcf file and phenotype file and they are exactly same. Could you please let me know how to solve this issue?
Krishna

**Comment by frankvogt** [comment]
@vinod1981 From v0.8.8 onwards the output directories don't contain spaces anymore and the percent symbol is removed aswell.

@krishna1925 Could you update vcf2gwas (`conda update vcf2gwas -c bioconda -c conda-forge -c fvogt257`) and check if the issue remains?
