### ISSUE TITLE
hello, I have recently been trying to use vcf2gwas, but I have encountered the following issues. Can you please advise me on how to solve them?

### ISSUE THREAD

**Issue by zxljiqixuexi** [frankvogt/vcf2gwas#19]
hello, I have recently been trying to use vcf2gwas, but I have encountered the following issues. Can you please advise me on how to solve them?

vcf2gwas v0.8.8 

Initialising..

Traceback (most recent call last):
  File "/home/zxl/miniconda3/bin/vcf2gwas", line 10, in <module>
    sys.exit(run_main())
  File "/home/zxl/miniconda3/lib/python3.9/site-packages/vcf2gwas/__main__.py", line 73, in run_main
    sys.exit(main(timestamp))
  File "/home/zxl/miniconda3/lib/python3.9/site-packages/vcf2gwas/__main__.py", line 39, in main
    P = Parser(argvals)
  File "/home/zxl/miniconda3/lib/python3.9/site-packages/vcf2gwas/parsing.py", line 225, in __init__
    self.args = getArgs(args)
  File "/home/zxl/miniconda3/lib/python3.9/site-packages/vcf2gwas/parsing.py", line 99, in getArgs
    "-M", "--memory", metavar="<int>", type=int, default=int(((virtual_memory().total/1e9)//2)*1e3), 
  File "/home/zxl/miniconda3/lib/python3.9/site-packages/psutil/__init__.py", line 1963, in virtual_memory
    ret = _psplatform.virtual_memory()
  File "/home/zxl/miniconda3/lib/python3.9/site-packages/psutil/_pslinux.py", line 435, in virtual_memory
    mems[fields[0]] = int(fields[1]) * 1024
IndexError: list index out of range

**Comment by frankvogt** [comment]
Hi, seems like there is a problem with psutil.
On what OS are you running vcf2gwas or are you running it in a container, respectively?
Could you also send me your command line input?

**Comment by zxljiqixuexi** [comment]
Everything is normal when we run vcf2gwas on the personal computer, but there is a problem on the server.
(base) zxl@shpc-407-instance-TOCY9lcr:~$ vcf2gwas

vcf2gwas v0.8.8 
Initialising..
Traceback (most recent call last):
  File "/home/zxl/miniconda3/bin/vcf2gwas", line 10, in <module>
    sys.exit(run_main())
  File "/home/zxl/miniconda3/lib/python3.9/site-packages/vcf2gwas/__main__.py", line 73, in run_main
    sys.exit(main(timestamp))
  File "/home/zxl/miniconda3/lib/python3.9/site-packages/vcf2gwas/__main__.py", line 39, in main
    P = Parser(argvals)
  File "/home/zxl/miniconda3/lib/python3.9/site-packages/vcf2gwas/parsing.py", line 225, in __init__
    self.args = getArgs(args)
  File "/home/zxl/miniconda3/lib/python3.9/site-packages/vcf2gwas/parsing.py", line 99, in getArgs
    "-M", "--memory", metavar="<int>", type=int, default=int(((virtual_memory().total/1e9)//2)*1e3), 
  File "/home/zxl/miniconda3/lib/python3.9/site-packages/psutil/__init__.py", line 1963, in virtual_memory
    ret = _psplatform.virtual_memory()
  File "/home/zxl/miniconda3/lib/python3.9/site-packages/psutil/_pslinux.py", line 435, in virtual_memory
    mems[fields[0]] = int(fields[1]) * 1024
IndexError: list index out of range

(base) zxl@shpc-407-instance-TOCY9lcr:~$ vcf2gwas -v test
vcf2gwas v0.8.8 
Initialising..
Copying example input files to current working directory..
Copying README and LICENSE files..
Collecting package metadata (current_repodata.json): done
Solving environment: | 
Warning: >10 possible package resolutions (only showing differing packages):
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::libiconv-1.17-h166bdaf_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::libnsl-2.0.0-h7f98852_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-14.2.4-h0b41bf4_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-cpp-14.2.4-hcb278e6_0
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::libiconv-1.17-h166bdaf_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::libnsl-2.0.0-h7f98852_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-14.2.4-h0b41bf4_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-cpp-14.2.4-hcb278e6_0
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::libnsl-2.0.0-h7f98852_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::libiconv-1.17-h166bdaf_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-14.2.4-h0b41bf4_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-cpp-14.2.4-hcb278e6_0
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::libiconv-1.17-h166bdaf_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::libnsl-2.0.0-h7f98852_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-14.2.4-h0b41bf4_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-cpp-14.2.4-hcb278e6_0
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::libnsl-2.0.0-h7f98852_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-14.2.4-h0b41bf4_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::libiconv-1.17-h166bdaf_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-cpp-14.2.4-hcb278e6_0
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::libiconv-1.17-h166bdaf_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::libnsl-2.0.0-h7f98852_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-14.2.4-h0b41bf4_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-cpp-14.2.4-hcb278e6_0
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-14.2.4-h0b41bf4_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::libiconv-1.17-h166bdaf_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::libnsl-2.0.0-h7f98852_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-cpp-14.2.4-hcb278e6_0
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::libiconv-1.17-h166bdaf_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-14.2.4-h0b41bf4_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::libnsl-2.0.0-h7f98852_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-cpp-14.2.4-hcb278e6_0
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-14.2.4-h0b41bf4_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-cpp-14.2.4-hcb278e6_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::libiconv-1.17-h166bdaf_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::libnsl-2.0.0-h7f98852_0
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-cpp-14.2.4-hcb278e6_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::libiconv-1.17-h166bdaf_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::libnsl-2.0.0-h7f98852_0, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::reproc-14.2.4-h0b41bf4_0
  ... and othedone
# All requested packages already installed.
Traceback (most recent call last):
  File "/home/zxl/miniconda3/lib/python3.9/site-packages/vcf2gwas/utils.py", line 54, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/zxl/miniconda3/lib/python3.9/site-packages/vcf2gwas/starter.py", line 23, in <module>
    from vcf2gwas.utils import *
  File "/home/zxl/miniconda3/lib/python3.9/site-packages/vcf2gwas/utils.py", line 57, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'

But we have installed seaborn

**Comment by frankvogt** [comment]
Did you set up a new environment and run vcf2gwas in this environment as detailed under [Installation via conda](https://github.com/frankvogt/vcf2gwas#installation-via-conda)?
