### ISSUE TITLE
Problem installing in fresh conda environment.

### ISSUE THREAD

**Issue by dxter-zz** [frankvogt/vcf2gwas#23]
I installed a fresh copy of miniconda on 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux.

conda create -n gwas
conda activate gwas
conda info
     active environment : gwas
    active env location : /path/local/src/miniconda3/envs/gwas
            shell level : 3
       user config file : /path/.condarc
 populated config files : /path/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /path/local/src/miniconda3  (writable)
      conda av data dir : /path/local/src/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /path/local/src/miniconda3/pkgs
                          /path/.conda/pkgs
       envs directories : /path/local/src/miniconda3/envs
                          /path/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.9 Linux/5.15.0-58-generic ubuntu/22.04.1 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

conda install vcf2gwas -c conda-forge -c bioconda -c fvogt257

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | Killed

On windows with a miniconda that's been installed for awhile but still creating a new gwas environment and activating it gave:

conda install vcf2gwas -c conda-forge -c bioconda -c fvogt257

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError:

**Comment by jennifercalawa** [comment]
Hi, I had the same problem trying to install on a Mac:

(myenv) jennifercalawa@U-KXNRWWJ417 ~ % conda install vcf2gwas -c conda-forge -c bioconda -c fvogt257
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: 

(myenv) jennifercalawa@U-KXNRWWJ417 ~ % conda install vcf2gwas -c conda-forge -c bioconda -c fvogt257 -v -vv -vvv
Traceback (most recent call last):
  File "/Users/jennifercalawa/anaconda3/lib/python3.10/site-packages/conda/gateways/logging.py", line 229, in set_verbosity
    set_all_logger_level(VERBOSITY_LEVELS[verbosity_level])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jennifercalawa/anaconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
    return func(*args, **kwargs)
  File "/Users/jennifercalawa/anaconda3/lib/python3.10/site-packages/conda/cli/main.py", line 62, in main_subshell
    init_loggers(context)
  File "/Users/jennifercalawa/anaconda3/lib/python3.10/site-packages/conda/cli/main.py", line 50, in init_loggers
    set_verbosity(context.verbosity)
  File "/Users/jennifercalawa/anaconda3/lib/python3.10/site-packages/conda/gateways/logging.py", line 231, in set_verbosity
    raise CondaError("Invalid verbosity level: %(verbosity_level)s",
conda.CondaError: Invalid verbosity level: 6

**Comment by frankvogt** [comment]
Could you re run the command with only either `-v`, `-vv`, or `-vvv` (not all 3 in the same command)? Maybe try first with only `-vv`.

**Comment by jennifercalawa** [comment]
My scientific computing department was able to get it installed and it worked! Thanks!
