### ISSUE TITLE
Running via docker is not working anymore

### ISSUE THREAD

**Issue by adrianodemarino** [frankvogt/vcf2gwas#29]
Before was working correctly but now when you run: 
` docker run -v /Users/adriano/Documents/git/vcf2gwas/:/vcf2gwas/ fvogt257/vcf2gwas -v test`
you will get this error:
```
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/vcf2gwas/utils.py", line 69, in <module>
    import umap
ModuleNotFoundError: No module named 'umap'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/vcf2gwas/starter.py", line 23, in <module>
    from vcf2gwas.utils import *
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/vcf2gwas/utils.py", line 72, in <module>
    import umap
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/umap/__init__.py", line 2, in <module>
    from .umap_ import UMAP
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/umap/umap_.py", line 28, in <module>
    import numba
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/numba/__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/numba/__init__.py", line 40, in _ensure_critical_deps
    raise ImportError(msg)
ImportError: Numba needs NumPy 1.21 or greater. Got NumPy 1.20.

vcf2gwas v0.8.8

Initialising..

Copying example input files to current working directory..
Copying README and LICENSE files..
```
The error occurs when the docker is preparing the env. 
Could you please share in the repo the docker file?, that will simplify things .

**Comment by samuelecancellieri** [comment]
I'm having the same issue, I think the problem is a conda package that got updated.
can you share the docker file to help solve the problem? @frankvogt

**Comment by frankvogt** [comment]
I updated the dependencies and uploaded the new version, everything should work again.
Additionally, the docker file can be found [here](https://github.com/frankvogt/vcf2gwas/tree/2117c10e1b2d83fc734bf4eeaee41fd748509580/files/Docker).
