### ISSUE TITLE
kmers_gwas.py cannot find a pheno.phenotypes_and_permutations file

### ISSUE THREAD

**Issue by tommydavies** [frankvogt/vcf2gwas#37]
Hi there, 

I am running the kmers_gwas.py script: 

sudo python2.7 /kmers_gwas.py --pheno phenotype.pheno --kmers_table kmers_table -l 31 -p 8 --outdir kmer_results

This throws the following error: 
Traceback (most recent call last):
  File "//src/py/align_kinship_phenotype.py", line 83, in <module>
    main()
  File "//src/py/align_kinship_phenotype.py", line 56, in main
    phenotype_val = get_column(args.fn_phenotype, 1)[1:] # Phenotypes values
  File "/src/py/functions.py", line 14, in get_column
    return [line.split(sep)[index] for line in file(fn,"r").read().split("\n")[:-1]]
IndexError: list index out of range
sh: 1: Rscript: not found
Traceback (most recent call last):
  File "/kmers_gwas.py", line 278, in <module>
    main()
  File "/kmers_gwas.py", line 107, in main
    phenotypes_names = file(paths["pheno_permuted_fn"] ,"r").read().split("\n")[0].split("\t")[1:]

IOError: [Errno 2] No such file or directory: 'kmer_results/pheno.phenotypes_and_permutations'

The manual does not mention any generation of such a file. Is there something I am missing? 

I have tried with phenotype data with NA's as well as without NA's. 

Please let me know why I might be getting this error. 

Thanks, 
Tommy

**Comment by tommydavies** [comment]
Hi all. If you experience the above error, check that your phenotype table does not have an extra newline (\n) at the end. It will produce the above error.

**Comment by tommydavies** [comment]
This was posted in the wrong place - the error code belongs to a different software. Please ignore this issue.
