### ISSUE TITLE
ChildProcessError

### ISSUE THREAD

**Issue by Lattesnow** [frankvogt/vcf2gwas#41]
Hi, 
There must be something wrong with my input file since the test data run successfully. 

Attached the error report here.
Running GEMMA

Phenotypes to analyze: urological_ageing

Creating relatedness matrix..
GEMMA 0.98.3 (2020-11-28) by Xiang Zhou and team (C) 2012-2020
Reading Files ...
## number of analyzed SNPs         =   828841
Calculating Relatedness Matrix ...
================================================== 100%
**** INFO: Done.
Relatedness matrix created successfully
Starting with urological_ageing analysis..
Output will be saved in output_gwas/Output/Linear_Mixed_Model/urological_ageing/urological_ageing_20240312_213650/
Reading relatedness matrix..
Calculating linear mixed model..
GEMMA 0.98.3 (2020-11-28) by Xiang Zhou and team (C) 2012-2020
Reading Files ...
## number of analyzed SNPs         =   828841
Start Eigen-Decomposition...
pve estimate =0.936558
se(pve) =1.24756e+06
GSL ERROR: domain error in beta.c at line 56 errno 1%
Traceback (most recent call last):
  File "/home/anaconda3/envs/p39/lib/python3.9/site-packages/vcf2gwas/analysis.py", line 398, in <module>
    Post_analysis.check_return_codes(pc_prefix, dir_temp)
  File "/home/anaconda3/envs/p39/lib/python3.9/site-packages/vcf2gwas/utils.py", line 1607, in check_return_codes
    raise ChildProcessError()
ChildProcessError

**Comment by Lattesnow** [comment]
Is there a way to run step by step?
